env:
  browser: true
  es2020: true
  node: true
  jest: true
extends:
  - standard
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/react-in-jsx-scope: off
  react/prop-types: 0
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars': error
globals:
  React: writable
